language: node_js
node_js:
  - '0.11'
env:
  global:
    - secure: "B7uivxLKTXQaTdWAjRTZ00CCLr0YPgUL91JSjKheqhrwzaLoJc/1pog9XVRHQztol/u3sAak5kVHRxrB27KrPGojy+LiRgQucFmTviLi9gNXGF4N799A8VdsU5P09mLrEoLF1I/KlOBaJwsHLgRyK2hHczbSYMxwD8qLN7v8bSU="
after_success:
  "export RSYNC_PASSWORD=$PASSWORD"
  "gulp rsync --destination=sazhinet@sazhi.net::sazhinet"
